### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by thom493** [fdescaves/DofusBuddy#1]
Hey! It's a very nice project you have here, but I can't seem to make it run after building. The main window doesn't open, and basically, nothing happens. I haven't been able to catch the bug yet since I'm not very familiar with C#.

**Comment by fdescaves** [comment]
Hey @thom493 ! I will look into it soon, I suppose that an error is thrown at the startup related to the configuration file or something like that. Please note that I'm no longer actively supporting it since I no longer use it. As far as I remember there's one thing that may also break: the ip adress of the game server was hard-coded (https://github.com/fdescaves/DofusBuddy/blob/5f6d00caa7f0373ca35a17a3db6bcd480c72112b/src/DofusBuddy/Managers/PacketManager.cs#L44) and it may have changed since I played.

**Comment by fdescaves** [comment]
@thom493 The issue you were facing should be fixed in the [1.8.0 release](https://github.com/fdescaves/DofusBuddy/releases/tag/v1.8.0). 
I've added an input to configure the game server IP Address it in the settings if it's no longer `172.65.242.238`  (you can use a tool like Wireshark to find it). If it's modified don't forget to restart DofusBuddy, hope everything will be OK from now on 🙂

**Comment by thom493** [comment]
Thank you ! It did fix the issue. I created a fork of your project where I added few extra features for the people who are interested. https://github.com/thom493/DofusBuddyOrigin
